### ISSUE TITLE
Custom pipeline documentation

### ISSUE THREAD

**Issue by gokul0** [RasaHQ/starter-pack-rasa-stack#35]
Hi,

My team and I are trying to build an NLP with RASA along with a custom pipeline. There is very little help that we can get from the official documentation. Can you provide an example in the starter-pack or somewhere else?

**Comment by MetcalfeTom** [comment]
Hi @gokul0,

So you know which components you'd like to use?  To change the pipeline you just need to edit `nlu_config.yml` with the component names, for example:

```yaml
language: "en"

pipeline:
- name: "nlp_mitie"
    model: "data/total_word_feature_extractor.dat"
- name: "tokenizer_mitie"
- name: "ner_mitie"
- name: "ner_synonyms"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_mitie"
- name: "intent_classifier_sklearn"
```
